const initialState = {
  a1: "w-rook",
  h1: "w-rook",
  a8: "b-rook",
  h8: "b-rook",
  b1: "w-knight",
  g1: "w-knight",
  b8: "b-knight",
  g8: "b-knight",
  c1: "w-bishop",
  f1: "w-bishop",
  c8: "b-bishop",
  f8: "b-bishop",
  d1: "w-queen",
  d8: "b-queen",
  e1: "w-king",
  e8: "b-king",
  a2: "w-pawn",
  b2: "w-pawn",
  c2: "w-pawn",
  d2: "w-pawn",
  e2: "w-pawn",
  f2: "w-pawn",
  g2: "w-pawn",
  h2: "w-pawn",
  a7: "b-pawn",
  b7: "b-pawn",
  c7: "b-pawn",
  d7: "b-pawn",
  e7: "b-pawn",
  f7: "b-pawn",
  g7: "b-pawn",
  h7: "b-pawn",
};

export default initialState;
